on: push
name: Check Assignment

jobs:
  check-allowed-files:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    steps:
      - uses: actions/checkout@v3
      - name: Run allowed-files & TODO check
        run: |
          python check_allowed_files.py \
            "hw-01.ipynb" \
            "README.md" \
            "data/*" \
            "images/*" \
            "check_allowed_files.py" \
            "requirements.txt" \
            "reports/*"
